name: Build Windows Application

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: 

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2

    - name: Install MSVC Compiler
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Qt 6 Framework
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3' 
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Configure CMake Project
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF ..

    - name: Compile and Build App
      run: |
        cd build
        cmake --build . --config Release

    - name: Clean and Package Binary
      run: |
        cd build
        if (Test-Path "src/Release") { cd src/Release } else { cd Release }
        if (Test-Path "RcloneBrowser.pdb") { Remove-Item "RcloneBrowser.pdb" }
        windeployqt --release RcloneBrowser.exe
        cd ../..
        Compress-Archive -Path build/src/Release/* -DestinationPath build/RcloneBrowser-Windows.zip

    - name: Upload Finished Application
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Build-Binary
        path: build/RcloneBrowser-Windows.zip
